# Import all node classes (NodeBypasser is frontend-only)
from .nodes import (
    KNF_Organizer,
    GeminiVideoCaptioner,
    NODE_CLASS_MAPPINGS as NODES_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as NODES_DISPLAY_NAME_MAPPINGS
)

# Import memory monitor nodes
from .memory_monitor import (
    NODE_CLASS_MAPPINGS as MEMORY_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MEMORY_DISPLAY_NAME_MAPPINGS
)

# Import committed noise nodes (for chunk consistency)
from .committed_noise import (
    NODE_CLASS_MAPPINGS as COMMITTED_NOISE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as COMMITTED_NOISE_DISPLAY_NAME_MAPPINGS
)

# Import RoPE utility nodes (for temporal position alignment)
from .rope_utils import (
    NODE_CLASS_MAPPINGS as ROPE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ROPE_DISPLAY_NAME_MAPPINGS
)

# Import reference latent nodes (Phase 2: attention context injection)
from .reference_latent import (
    NODE_CLASS_MAPPINGS as REFERENCE_LATENT_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REFERENCE_LATENT_DISPLAY_NAME_MAPPINGS
)

# Import attention guidance nodes (EXPERIMENTAL - low-res attention pattern transfer)
from .attention_guidance import (
    NODE_CLASS_MAPPINGS as ATTENTION_GUIDANCE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ATTENTION_GUIDANCE_DISPLAY_NAME_MAPPINGS
)

# Import latent guidance nodes (lightweight alternative to attention guidance)
from .latent_guidance import (
    NODE_CLASS_MAPPINGS as LATENT_GUIDANCE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LATENT_GUIDANCE_DISPLAY_NAME_MAPPINGS
)

# Import overlap attention nodes (chunk boundary consistency)
from .overlap_attention import (
    NODE_CLASS_MAPPINGS as OVERLAP_ATTENTION_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as OVERLAP_ATTENTION_DISPLAY_NAME_MAPPINGS
)

# Import sweep automation nodes (parameter sweep planner/loader/recorder)
from .sweep_planner import (
    NODE_CLASS_MAPPINGS as SWEEP_PLANNER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SWEEP_PLANNER_DISPLAY_NAME_MAPPINGS
)
from .sweep_loader import (
    NODE_CLASS_MAPPINGS as SWEEP_LOADER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SWEEP_LOADER_DISPLAY_NAME_MAPPINGS
)
from .sweep_recorder import (
    NODE_CLASS_MAPPINGS as SWEEP_RECORDER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SWEEP_RECORDER_DISPLAY_NAME_MAPPINGS
)

# Import sweep contact sheet nodes (visual comparison grid)
from .sweep_contact_sheet import (
    NODE_CLASS_MAPPINGS as SWEEP_CONTACT_SHEET_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SWEEP_CONTACT_SHEET_DISPLAY_NAME_MAPPINGS
)

# Import latent utility nodes (for VACE reference image workflows)
from .latent_utils import (
    NODE_CLASS_MAPPINGS as LATENT_UTILS_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LATENT_UTILS_DISPLAY_NAME_MAPPINGS
)

# Import stitcher I/O nodes (for saving/loading STITCHER objects from inpaint-crop)
from .stitcher_io import (
    NODE_CLASS_MAPPINGS as STITCHER_IO_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as STITCHER_IO_DISPLAY_NAME_MAPPINGS
)

# Import text overlay nodes (forked from comfyui-textoverlay)
from .text_overlay import (
    NODE_CLASS_MAPPINGS as TEXT_OVERLAY_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TEXT_OVERLAY_DISPLAY_NAME_MAPPINGS
)

# Import bbox creator nodes (interactive bounding box with aspect ratio constraints)
from .bbox_creator import (
    NODE_CLASS_MAPPINGS as BBOX_CREATOR_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BBOX_CREATOR_DISPLAY_NAME_MAPPINGS
)

# Import inpaint crop v2 nodes (simplified inpaint-focused crop with bounding box control)
from .inpaint_crop import (
    NODE_CLASS_MAPPINGS as INPAINT_CROP_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as INPAINT_CROP_DISPLAY_NAME_MAPPINGS
)

# Import resolution verifier nodes (adjust dimensions to be divisible by specified value)
from .resolution_verifier import (
    NODE_CLASS_MAPPINGS as RESOLUTION_VERIFIER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as RESOLUTION_VERIFIER_DISPLAY_NAME_MAPPINGS
)

# Merge all node mappings
NODE_CLASS_MAPPINGS = {
    **NODES_CLASS_MAPPINGS,
    **MEMORY_CLASS_MAPPINGS,
    **COMMITTED_NOISE_CLASS_MAPPINGS,
    **ROPE_CLASS_MAPPINGS,
    **REFERENCE_LATENT_CLASS_MAPPINGS,
    **ATTENTION_GUIDANCE_CLASS_MAPPINGS,
    **LATENT_GUIDANCE_CLASS_MAPPINGS,
    **OVERLAP_ATTENTION_CLASS_MAPPINGS,
    **SWEEP_PLANNER_CLASS_MAPPINGS,
    **SWEEP_LOADER_CLASS_MAPPINGS,
    **SWEEP_RECORDER_CLASS_MAPPINGS,
    **SWEEP_CONTACT_SHEET_CLASS_MAPPINGS,
    **LATENT_UTILS_CLASS_MAPPINGS,
    **STITCHER_IO_CLASS_MAPPINGS,
    **TEXT_OVERLAY_CLASS_MAPPINGS,
    **BBOX_CREATOR_CLASS_MAPPINGS,
    **INPAINT_CROP_CLASS_MAPPINGS,
    **RESOLUTION_VERIFIER_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **NODES_DISPLAY_NAME_MAPPINGS,
    **MEMORY_DISPLAY_NAME_MAPPINGS,
    **COMMITTED_NOISE_DISPLAY_NAME_MAPPINGS,
    **ROPE_DISPLAY_NAME_MAPPINGS,
    **REFERENCE_LATENT_DISPLAY_NAME_MAPPINGS,
    **ATTENTION_GUIDANCE_DISPLAY_NAME_MAPPINGS,
    **LATENT_GUIDANCE_DISPLAY_NAME_MAPPINGS,
    **OVERLAP_ATTENTION_DISPLAY_NAME_MAPPINGS,
    **SWEEP_PLANNER_DISPLAY_NAME_MAPPINGS,
    **SWEEP_LOADER_DISPLAY_NAME_MAPPINGS,
    **SWEEP_RECORDER_DISPLAY_NAME_MAPPINGS,
    **SWEEP_CONTACT_SHEET_DISPLAY_NAME_MAPPINGS,
    **LATENT_UTILS_DISPLAY_NAME_MAPPINGS,
    **STITCHER_IO_DISPLAY_NAME_MAPPINGS,
    **TEXT_OVERLAY_DISPLAY_NAME_MAPPINGS,
    **BBOX_CREATOR_DISPLAY_NAME_MAPPINGS,
    **INPAINT_CROP_DISPLAY_NAME_MAPPINGS,
    **RESOLUTION_VERIFIER_DISPLAY_NAME_MAPPINGS,
}

# Export the mappings for ComfyUI
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']